- hosts: localhost
  become: false
  vars:
    generate_mininet_configs: true
    mininet_config_dir: './mininet/mininet_configs'
  tasks:
    - name: Ensuring Mininet Config Folder Exists
      file:
        path: "{{ mininet_config_dir }}/{{ item.name }}"
        state: "directory"
      with_items: '{{ quagga_bgp_router_configs }}'
      when: generate_mininet_configs

    - name: Generating Mininet Configs
      template:
        src: "./mininet.cfg.j2"
        dest: "{{ mininet_config_dir }}/{{ item.name }}/Quagga.conf"
      with_items: '{{ quagga_bgp_router_configs }}'

    - name: Generating Mininet Daemon Configs
      template:
        src: "./daemons.j2"
        dest: "{{ mininet_config_dir }}/{{ item.name }}/daemons.conf"
      with_items: '{{ quagga_bgp_router_configs }}'
