---
- hosts: quagga-routers
  remote_user: vagrant
  become: true
  vars:
  roles:
    - role: ansible-bootstrap
    - role: ansible-base
    - role: ansible-quagga
  tasks:
    - name: installing packages
      apt:
        name: "{{ item }}"
        state: "present"
      with_items:
        - 'traceroute'
