---
anycast_service_vip_1: '172.16.200.101'
quagga_bgp_as_groups:
  compute_1: '64513'
  compute_2: '64514'
  leaf_1: '64513'
  leaf_2: '64514'
  spine_1: '64512'
  spine_2: '64515'
quagga_debugging:
  bgp:
    enabled: false
    debug:
      # - 'as4'
      # - 'as4 segment'
      - 'events'
      # - 'filters'
      # - 'fsm'
      - 'keepalives'
      - 'updates'
      # - 'updates in'
      # - 'updates out'
      # - 'zebra'
  ospf:
    enabled: false
    debug:
      - 'event'
      # - 'ism'
      # - 'ism events'
      # - 'ism status'
      # - 'ism timers'
      # - 'lsa'
      # - 'lsa flooding'
      # - 'lsa generate'
      # - 'lsa install'
      # - 'lsa refresh'
      # - 'nsm'
      # - 'nsm events'
      # - 'nsm status'
      # - 'nsm timers'
      # - 'nssa'
      # - 'packet all'
      # - 'packet all detail'
      # - 'packet all recv'
      # - 'packet all send'
      # - 'packet dd'
      # - 'packet dd detail'
      # - 'packet dd recv'
      # - 'packet dd send'
      # - 'packet hello'
      # - 'packet hello detail'
      # - 'packet hello recv'
      # - 'packet hello send'
      # - 'packet ls-ack'
      # - 'packet ls-ack detail'
      # - 'packet ls-ack recv'
      # - 'packet ls-ack send'
      # - 'packet ls-request'
      # - 'packet ls-request detail'
      # - 'packet ls-request recv'
      # - 'packet ls-request send'
      # - 'packet ls-update'
      # - 'packet ls-update detail'
      # - 'packet ls-update recv'
      # - 'packet ls-update send'
  zebra:
    enabled: true
    debug:
      - 'events'
      # - 'fpm'
      - 'kernel'
      # - 'packet'
      # - 'packet recv'
      # - 'packet send'
      # - 'rib'
      # - 'rib queue'
quagga_ip_forwarding:
  ipv4: true
  ipv6: true
quagga_node_info:
  node0:
    router_id: '10.0.0.10'
    spine_1_ip: '192.168.1.10'
  node1:
    compute_1_ip: '192.168.10.11'
    router_id: '10.1.1.11'
    spine_1_ip: '192.168.1.11'
    spine_2_ip: '192.168.2.11'
  node2:
    compute_2_ip: '192.168.20.12'
    router_id: '10.2.2.12'
    spine_1_ip: '192.168.1.12'
    spine_2_ip: '192.168.2.12'
  node3:
    compute_1_ip: '192.168.10.13'
    router_id: '10.3.3.13'
    workloads_3_ip: '192.168.30.13'
  node4:
    compute_2_ip: '192.168.20.14'
    router_id: '10.4.4.14'
    workloads_4_ip: '192.168.40.14'
  node5:
    compute_1_ip: '192.168.10.15'
    router_id: '10.5.5.15'
    workloads_5_ip: '192.168.50.15'
  node6:
    compute_2_ip: '192.168.20.16'
    router_id: '10.6.6.16'
    workloads_6_ip: '192.168.60.16'
  node7:
    router_id: '10.7.7.17'
    spine_2_ip: '192.168.2.17'
  node8:
    compute_1_ip: '192.168.10.18'
    router_id: '10.8.8.18'
    spine_1_ip: '192.168.1.18'
    spine_2_ip: '192.168.2.18'
  node9:
    compute_2_ip: '192.168.20.19'
    router_id: '10.9.9.19'
    spine_1_ip: '192.168.1.19'
    spine_2_ip: '192.168.2.19'
quagga_bgp_router_configs:
  - name: 'node0'
    local_as: '{{ quagga_bgp_as_groups.spine_1 }}'
    neighbors:
      - neighbor: '{{ quagga_node_info.node1.spine_1_ip }}'
        announce_default_route: false
        description: 'leaf-1-node1'
        remote_as: '{{ quagga_bgp_as_groups.leaf_1 }}'
      - neighbor: '{{ quagga_node_info.node2.spine_1_ip }}'
        announce_default_route: false
        description: 'leaf-2-node2'
        remote_as: '{{ quagga_bgp_as_groups.leaf_2 }}'
      - neighbor: '{{ quagga_node_info.node8.spine_1_ip }}'
        announce_default_route: false
        description: 'leaf-1-node8'
        remote_as: '{{ quagga_bgp_as_groups.leaf_1 }}'
      - neighbor: '{{ quagga_node_info.node9.spine_1_ip }}'
        announce_default_route: false
        description: 'leaf-2-node9'
        remote_as: '{{ quagga_bgp_as_groups.leaf_2 }}'
    network_advertisements:  #networks to advertise
      - '192.168.1.0/24'
    router_id: '{{ quagga_node_info.node0.router_id }}'
  - name: 'node1'
    local_as: '{{ quagga_bgp_as_groups.leaf_1 }}'
    neighbors:
      - neighbor: '{{ quagga_node_info.node0.spine_1_ip }}'
        announce_default_route: false
        description: 'spine-1-node0'
        remote_as: '{{ quagga_bgp_as_groups.spine_1 }}'
      - neighbor: '{{ quagga_node_info.node7.spine_2_ip }}'
        announce_default_route: false
        description: 'spine-2-node7'
        remote_as: '{{ quagga_bgp_as_groups.spine_2 }}'
      - neighbor: '{{ quagga_node_info.node3.compute_1_ip }}'
        announce_default_route: false
        description: 'compute-1-node3'
        remote_as: '{{ quagga_bgp_as_groups.compute_1 }}'
      - neighbor: '{{ quagga_node_info.node5.compute_1_ip }}'
        announce_default_route: false
        description: 'compute-1-node5'
        remote_as: '{{ quagga_bgp_as_groups.compute_1 }}'
    network_advertisements:  #networks to advertise
      - '192.168.10.0/24'
    router_id: '{{ quagga_node_info.node1.router_id }}'
  - name: 'node2'
    local_as: '{{ quagga_bgp_as_groups.leaf_2 }}'
    neighbors:
      - neighbor: '{{ quagga_node_info.node0.spine_1_ip }}'
        announce_default_route: false
        description: 'spine-1-node0'
        remote_as: '{{ quagga_bgp_as_groups.spine_1 }}'
      - neighbor: '{{ quagga_node_info.node7.spine_2_ip }}'
        announce_default_route: false
        description: 'spine-2-node7'
        remote_as: '{{ quagga_bgp_as_groups.spine_2 }}'
      - neighbor: '{{ quagga_node_info.node4.compute_2_ip }}'
        announce_default_route: false
        description: 'compute-2-node4'
        remote_as: '{{ quagga_bgp_as_groups.compute_2 }}'
      - neighbor: '{{ quagga_node_info.node6.compute_2_ip }}'
        announce_default_route: false
        description: 'compute-2-node6'
        remote_as: '{{ quagga_bgp_as_groups.compute_2 }}'
    network_advertisements:  #networks to advertise
      - '192.168.20.0/24'
    router_id: '{{ quagga_node_info.node2.router_id }}'
  - name: 'node3'
    local_as: '{{ quagga_bgp_as_groups.compute_1 }}'
    neighbors:
      - neighbor: '{{ quagga_node_info.node1.compute_1_ip }}'
        announce_default_route: false
        description: 'leaf-1-node1'
        remote_as: '{{ quagga_bgp_as_groups.leaf_1 }}'
      - neighbor: '{{ quagga_node_info.node8.compute_1_ip }}'
        announce_default_route: false
        description: 'leaf-1-node8'
        remote_as: '{{ quagga_bgp_as_groups.leaf_1 }}'
    network_advertisements:  #networks to advertise
      - '{{ anycast_service_vip_1 }}/32'
      - '192.168.30.0/24'
    router_id: '{{ quagga_node_info.node3.router_id }}'
  - name: 'node4'
    local_as: '{{ quagga_bgp_as_groups.compute_2 }}'
    neighbors:
      - neighbor: '{{ quagga_node_info.node2.compute_2_ip }}'
        announce_default_route: false
        description: 'leaf-2-node2'
        remote_as: '{{ quagga_bgp_as_groups.leaf_2 }}'
      - neighbor: '{{ quagga_node_info.node9.compute_2_ip }}'
        announce_default_route: false
        description: 'leaf-2-node9'
        remote_as: '{{ quagga_bgp_as_groups.leaf_2 }}'
    network_advertisements:  #networks to advertise
      - '{{ anycast_service_vip_1 }}/32'
      - '192.168.40.0/24'
    router_id: '{{ quagga_node_info.node4.router_id }}'
  - name: 'node5'
    local_as: '{{ quagga_bgp_as_groups.compute_1 }}'
    neighbors:
      - neighbor: '{{ quagga_node_info.node1.compute_1_ip }}'
        announce_default_route: false
        description: 'leaf-1-node1'
        remote_as: '{{ quagga_bgp_as_groups.leaf_1 }}'
      - neighbor: '{{ quagga_node_info.node8.compute_1_ip }}'
        announce_default_route: false
        description: 'leaf-1-node8'
        remote_as: '{{ quagga_bgp_as_groups.leaf_1 }}'
    network_advertisements:  #networks to advertise
      - '{{ anycast_service_vip_1 }}/32'
      - '192.168.50.0/24'
    router_id: '{{ quagga_node_info.node5.router_id }}'
  - name: 'node6'
    local_as: '{{ quagga_bgp_as_groups.compute_2 }}'
    neighbors:
      - neighbor: '{{ quagga_node_info.node2.compute_2_ip }}'
        announce_default_route: false
        description: 'leaf-2-node2'
        remote_as: '{{ quagga_bgp_as_groups.leaf_2 }}'
      - neighbor: '{{ quagga_node_info.node9.compute_2_ip }}'
        announce_default_route: false
        description: 'leaf-2-node9'
        remote_as: '{{ quagga_bgp_as_groups.leaf_2 }}'
    network_advertisements:  #networks to advertise
      - '{{ anycast_service_vip_1 }}/32'
      - '192.168.60.0/24'
    router_id: '{{ quagga_node_info.node6.router_id }}'
  - name: 'node7'
    local_as: '{{ quagga_bgp_as_groups.spine_2 }}'
    description: 'spine-1-node7'
    neighbors:
      - neighbor: '{{ quagga_node_info.node1.spine_2_ip }}'
        announce_default_route: false
        description: 'leaf-1-node1'
        remote_as: '{{ quagga_bgp_as_groups.leaf_1 }}'
      - neighbor: '{{ quagga_node_info.node2.spine_2_ip }}'
        announce_default_route: false
        description: 'leaf-2-node2'
        remote_as: '{{ quagga_bgp_as_groups.leaf_2 }}'
      - neighbor: '{{ quagga_node_info.node8.spine_2_ip }}'
        announce_default_route: false
        description: 'leaf-1-node8'
        remote_as: '{{ quagga_bgp_as_groups.leaf_1 }}'
      - neighbor: '{{ quagga_node_info.node9.spine_2_ip }}'
        announce_default_route: false
        description: 'leaf-2-node9'
        remote_as: '{{ quagga_bgp_as_groups.leaf_2 }}'
    network_advertisements:  #networks to advertise
      - '192.168.2.0/24'
    router_id: '{{ quagga_node_info.node7.router_id }}'
  - name: 'node8'
    local_as: '{{ quagga_bgp_as_groups.leaf_1 }}'
    neighbors:
      - neighbor: '{{ quagga_node_info.node0.spine_1_ip }}'
        announce_default_route: false
        description: 'spine-1-node0'
        remote_as: '{{ quagga_bgp_as_groups.spine_1 }}'
      - neighbor: '{{ quagga_node_info.node7.spine_2_ip }}'
        announce_default_route: false
        description: 'spine-2-node7'
        remote_as: '{{ quagga_bgp_as_groups.spine_2 }}'
      - neighbor: '{{ quagga_node_info.node3.compute_1_ip }}'
        announce_default_route: false
        description: 'compute-1-node3'
        remote_as: '{{ quagga_bgp_as_groups.compute_1 }}'
      - neighbor: '{{ quagga_node_info.node5.compute_1_ip }}'
        announce_default_route: false
        description: 'compute-1-node5'
        remote_as: '{{ quagga_bgp_as_groups.compute_1 }}'
    network_advertisements:  #networks to advertise
      - '192.168.10.0/24'
    router_id: '{{ quagga_node_info.node8.router_id }}'
  - name: 'node9'
    local_as: '{{ quagga_bgp_as_groups.leaf_2 }}'
    neighbors:
      - neighbor: '{{ quagga_node_info.node0.spine_1_ip }}'
        announce_default_route: false
        description: 'spine-1-node0'
        remote_as: '{{ quagga_bgp_as_groups.spine_1 }}'
      - neighbor: '{{ quagga_node_info.node7.spine_2_ip }}'
        announce_default_route: false
        description: 'spine-2-node7'
        remote_as: '{{ quagga_bgp_as_groups.spine_2 }}'
      - neighbor: '{{ quagga_node_info.node4.compute_2_ip }}'
        announce_default_route: false
        description: 'compute-2-node4'
        remote_as: '{{ quagga_bgp_as_groups.compute_2 }}'
      - neighbor: '{{ quagga_node_info.node6.compute_2_ip }}'
        announce_default_route: false
        description: 'compute-2-node6'
        remote_as: '{{ quagga_bgp_as_groups.compute_2 }}'
    network_advertisements:  #networks to advertise
      - '192.168.20.0/24'
    router_id: '{{ quagga_node_info.node9.router_id }}'
quagga_config_bgpd: true #defines if quagga bgpd should be configured based on quagga_bgp_router_configs...makes it easy to disable auto routing in order to define your routes manually
quagga_config_interfaces: true
quagga_config_ospfd: false  #defines if quagga ospfd should be configured based on quagga_ospf_ vars...makes it easy to disable auto routing in order to define your routes manually
quagga_config: true

# Defines if quagga_interfaces are defined within Quagga configuration or
# /etc/network/interfaces.d/
quagga_defined_interfaces: true

quagga_enable_bgpd: true
quagga_enable_ospfd: false
quagga_enable_password: 'quagga' #define here or in group_vars/group
quagga_logging:
  facility:
    enabled: false
    facility: 'daemon' # auth|cron|daemon|kern|local0|local1|local2|local3|local4|local5|local6|local7|lpr|mail|news|syslog|user|uucp
  file:
    enabled: true
    filename: '/var/log/quagga/zebra.log'
    level: 'debugging' # alerts|critical|debugging|emergencies|errors|informational|notifications|warnings
  monitor:
    enabled: false
    level: 'debugging' # alerts|critical|debugging|emergencies|errors|informational|notifications|warnings
  record_priority: false
  stdout:
    enabled: false
    level: 'debugging' # alerts|critical|debugging|emergencies|errors|informational|notifications|warnings
  syslog:
    enabled: false
    level: 'debugging' # alerts|critical|debugging|emergencies|errors|informational|notifications|warnings
  timestamp:
    enabled: false
    precision: 0 # 0-6
  trap:
    enabled: false
    level: 'debugging' # alerts|critical|debugging|emergencies|errors|informational|notifications|warnings
quagga_password: 'quagga' #define in group_vars/all/accounts
