---
quagga_interfaces_lo:
  - int: "lo{{ ':' }}0"
    address: '10.3.3.13/32'
    method: 'static'
    configure: true
quagga_ospf_area_config:
  - network: '192.168.3.0/24'
    area: '{{ quagga_ospf_area }}'
quagga_ospf_routerid: '10.3.3.13'
