---
quagga_bgp_router_configs:
  - name: 'node0'
    local_as: '64512'
    neighbors:
      - neighbor: '192.168.1.11'
        announce_default_route: false
        description: 'leaf-1-node1'
        remote_as: '64513'
      - neighbor: '192.168.1.12'
        announce_default_route: false
        description: 'leaf-2-node2'
        remote_as: '64514'
      - neighbor: '192.168.1.18'
        announce_default_route: false
        description: 'leaf-1-node8'
        remote_as: '64513'
      - neighbor: '192.168.1.19'
        announce_default_route: false
        description: 'leaf-2-node9'
        remote_as: '64514'
    network_advertisements:  #networks to advertise
      - '192.168.1.0/24'
    router_id: '10.0.0.10'
  - name: 'node1'
    local_as: '64513'
    neighbors:
      - neighbor: '192.168.1.10'
        announce_default_route: false
        description: 'spine-1-node0'
        remote_as: '64512'
      - neighbor: '192.168.2.17'
        announce_default_route: false
        description: 'spine-2-node7'
        remote_as: '64515'
      - neighbor: '192.168.10.13'
        announce_default_route: false
        description: 'compute-1-node3'
        remote_as: '64513'
      - neighbor: '192.168.10.15'
        announce_default_route: false
        description: 'compute-1-node5'
        remote_as: '64513'
    network_advertisements:  #networks to advertise
      - '192.168.10.0/24'
    router_id: '10.1.1.11'
  - name: 'node2'
    local_as: '64514'
    neighbors:
      - neighbor: '192.168.1.10'
        announce_default_route: false
        description: 'spine-1-node0'
        remote_as: '64512'
      - neighbor: '192.168.2.17'
        announce_default_route: false
        description: 'spine-2-node7'
        remote_as: '64515'
      - neighbor: '192.168.20.14'
        announce_default_route: false
        description: 'compute-2-node4'
        remote_as: '64514'
      - neighbor: '192.168.20.16'
        announce_default_route: false
        description: 'compute-2-node6'
        remote_as: '64514'
    network_advertisements:  #networks to advertise
      - '192.168.20.0/24'
    router_id: '10.2.2.12'
  - name: 'node3'
    local_as: '64513'
    neighbors:
      - neighbor: '192.168.10.11'
        announce_default_route: false
        description: 'leaf-1-node1'
        remote_as: '64513'
      - neighbor: '192.168.10.18'
        announce_default_route: false
        description: 'leaf-1-node8'
        remote_as: '64513'
    network_advertisements:  #networks to advertise
      - '192.168.30.0/24'
    router_id: '10.3.3.13'
  - name: 'node4'
    local_as: '64514'
    neighbors:
      - neighbor: '192.168.20.12'
        announce_default_route: false
        description: 'leaf-2-node2'
        remote_as: '64514'
      - neighbor: '192.168.20.19'
        announce_default_route: false
        description: 'leaf-2-node9'
        remote_as: '64514'
    network_advertisements:  #networks to advertise
      - '192.168.40.0/24'
    router_id: '10.4.4.14'
  - name: 'node5'
    local_as: '64513'
    neighbors:
      - neighbor: '192.168.10.11'
        announce_default_route: false
        description: 'leaf-1-node1'
        remote_as: '64513'
      - neighbor: '192.168.10.18'
        announce_default_route: false
        description: 'leaf-1-node8'
        remote_as: '64513'
    network_advertisements:  #networks to advertise
      - '192.168.50.0/24'
    router_id: '10.5.5.15'
  - name: 'node6'
    local_as: '64514'
    neighbors:
      - neighbor: '192.168.20.12'
        announce_default_route: false
        description: 'leaf-2-node2'
        remote_as: '64514'
      - neighbor: '192.168.20.19'
        announce_default_route: false
        description: 'leaf-2-node9'
        remote_as: '64514'
    network_advertisements:  #networks to advertise
      - '192.168.60.0/24'
    router_id: '10.6.6.16'
  - name: 'node7'
    local_as: '64515'
    description: 'spine-1-node7'
    neighbors:
      - neighbor: '192.168.2.11'
        announce_default_route: false
        description: 'leaf-1-node1'
        remote_as: '64513'
      - neighbor: '192.168.2.12'
        announce_default_route: false
        description: 'leaf-2-node2'
        remote_as: '64514'
      - neighbor: '192.168.2.18'
        announce_default_route: false
        description: 'leaf-1-node8'
        remote_as: '64513'
      - neighbor: '192.168.2.19'
        announce_default_route: false
        description: 'leaf-2-node9'
        remote_as: '64514'
    network_advertisements:  #networks to advertise
      - '192.168.2.0/24'
    router_id: '10.7.7.17'
  - name: 'node8'
    local_as: '64513'
    neighbors:
      - neighbor: '192.168.1.10'
        announce_default_route: false
        description: 'spine-1-node0'
        remote_as: '64512'
      - neighbor: '192.168.2.17'
        announce_default_route: false
        description: 'spine-2-node7'
        remote_as: '64515'
      - neighbor: '192.168.10.13'
        announce_default_route: false
        description: 'compute-1-node3'
        remote_as: '64513'
      - neighbor: '192.168.10.15'
        announce_default_route: false
        description: 'compute-1-node5'
        remote_as: '64513'
    network_advertisements:  #networks to advertise
      - '192.168.10.0/24'
    router_id: '10.8.8.18'
  - name: 'node9'
    local_as: '64514'
    neighbors:
      - neighbor: '192.168.1.10'
        announce_default_route: false
        description: 'spine-1-node0'
        remote_as: '64512'
      - neighbor: '192.168.2.17'
        announce_default_route: false
        description: 'spine-2-node7'
        remote_as: '64515'
      - neighbor: '192.168.20.14'
        announce_default_route: false
        description: 'compute-2-node4'
        remote_as: '64514'
      - neighbor: '192.168.20.16'
        announce_default_route: false
        description: 'compute-2-node6'
        remote_as: '64514'
    network_advertisements:  #networks to advertise
      - '192.168.20.0/24'
    router_id: '10.9.9.19'
quagga_config_bgpd: true #defines if quagga bgpd should be configured based on quagga_bgp_router_configs...makes it easy to disable auto routing in order to define your routes manually
quagga_config_interfaces: true
quagga_config_ospfd: false  #defines if quagga ospfd should be configured based on quagga_ospf_ vars...makes it easy to disable auto routing in order to define your routes manually
quagga_config: true

# Defines if quagga_interfaces are defined within Quagga configuration or
# /etc/network/interfaces.d/
quagga_defined_interfaces: true

quagga_enable_bgpd: true
quagga_enable_ospfd: false
