---
quagga_bgp_router_configs:
  - name: 'node0'
    local_as: '64512'
    neighbors:
      - neighbor: '192.168.1.11'
        announce_default_route: false
        description: 'leaf-1-node1'
        remote_as: '64513'
        # prefix_lists: # Define specific BGP neighbore prefix lists
        #   - name: 'FILTER01-out' # Define name of filter
        #     direction: 'out' # define direction (in|out)
        #     orf: 'send' # Define outbound route filter (send|receive|both)
      - neighbor: '192.168.2.12'
        announce_default_route: false
        description: 'leaf-2-node2'
        # prefix_lists:
        #   - name: 'FILTER02-in'
        #     direction: 'in'
        #     orf: 'receive'
        remote_as: '64514'
    network_advertisements:  #networks to advertise
      - '192.168.1.0/24'
      - '192.168.2.0/24'
    router_id: '10.0.0.10'
    # prefix_lists:
    #   - name: 'FILTER01-out'
    #     action: 'permit'
    #     network: '10.0.0.10/32'
    #     sequence: '10'
    #   - name: 'FILTER01-out'
    #     action: 'permit'
    #     network: '192.168.1.0/24'
    #     sequence: '20'
    #   - name: 'FILTER01-out'
    #     action: 'permit'
    #     network: '192.168.2.0/24'
    #     sequence: '30'
    #   - name: 'FILTER01-out'
    #     action: 'deny'
    #     network: 'any'
    #     sequence: '40'
  - name: 'node1'
    local_as: '64513'
    neighbors:
      - neighbor: '192.168.1.10'
        announce_default_route: false
        description: 'spine-1-node0'
        remote_as: '64512'
        # prefix_lists:
        #   - name: 'FILTER01-in'
        #     direction: 'in'
        #     orf: 'receive'
      - neighbor: '192.168.10.13'
        announce_default_route: false
        description: 'compute-1-node3'
        remote_as: '64513'
      - neighbor: '192.168.10.15'
        announce_default_route: false
        description: 'compute-1-node5'
        remote_as: '64513'
    network_advertisements:  #networks to advertise
      - '192.168.10.0/24'
    router_id: '10.1.1.11'
  - name: 'node2'
    local_as: '64514'
    neighbors:
      - neighbor: '192.168.2.10'
        announce_default_route: false
        description: 'spine-1-node0'
        # prefix_lists:
        #   - name: 'FILTER02-out'
        #     direction: 'out'
        #     orf: 'send'
        remote_as: '64512'
      - neighbor: '192.168.20.14'
        announce_default_route: false
        description: 'compute-2-node4'
        remote_as: '64514'
      - neighbor: '192.168.20.16'
        announce_default_route: false
        description: 'compute-2-node6'
        remote_as: '64514'
    network_advertisements:  #networks to advertise
      - '192.168.20.0/24'
    # prefix_lists:
    #   - name: 'FILTER02-out'
    #     action: 'permit'
    #     network: '192.168.2.0/24'
    #     sequence: '10'
    #   - name: 'FILTER01-out'
    #     action: 'deny'
    #     network: 'any'
    #     sequence: '20'
    router_id: '10.2.2.12'
  - name: 'node3'
    local_as: '64513'
    neighbors:
      - neighbor: '192.168.10.11'
        announce_default_route: false
        description: 'leaf-1-node1'
        remote_as: '64513'
    network_advertisements:  #networks to advertise
      - '192.168.30.0/24'
    router_id: '10.3.3.13'
  - name: 'node4'
    local_as: '64514'
    neighbors:
      - neighbor: '192.168.20.12'
        announce_default_route: false
        description: 'leaf-2-node2'
        remote_as: '64514'
    network_advertisements:  #networks to advertise
      - '192.168.40.0/24'
    router_id: '10.4.4.14'
  - name: 'node5'
    local_as: '64513'
    neighbors:
      - neighbor: '192.168.10.11'
        announce_default_route: false
        description: 'leaf-1-node1'
        remote_as: '64513'
    network_advertisements:  #networks to advertise
      - '192.168.50.0/24'
    router_id: '10.5.5.15'
  - name: 'node6'
    local_as: '64514'
    neighbors:
      - neighbor: '192.168.20.12'
        announce_default_route: false
        description: 'leaf-2-node2'
        remote_as: '64514'
    network_advertisements:  #networks to advertise
      - '192.168.60.0/24'
    router_id: '10.6.6.16'
quagga_config_bgpd: true #defines if quagga bgpd should be configured based on quagga_bgp_router_configs...makes it easy to disable auto routing in order to define your routes manually
quagga_config_interfaces: true
quagga_config_ospfd: false  #defines if quagga ospfd should be configured based on quagga_ospf_ vars...makes it easy to disable auto routing in order to define your routes manually
quagga_config: true

# Defines if quagga_interfaces are defined within Quagga configuration or
# /etc/network/interfaces.d/
quagga_defined_interfaces: true

quagga_enable_bgpd: true
quagga_enable_ospfd: false
